= Daniel Pyone Maung - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Giatros by CS2103 AY1819S2 W13-4

---

== Overview

Giatros is a desktop patient record application used to keep track of patient data in a hospital. Written in Java, the user interacts with it using a CLI, and it has a GUI created with JavaFX.
One of the main features of Giatros is its ability to track various appointments for each patient, something that medical professionals often overlook. This may lead to tragedy, such as deathdue to drug allergy,
as seen in this https://www.straitstimes.com/singapore/courts-crime/womans-death-from-drug-allergy-found-to-be-a-medical-misadventure[news article]. Moreover, hospitals have a large number of patients, thereby staff can be easily overwhelmed, thus requiring a systematic way to make and manage appointments for instance.
This software is built upon an existing application: Address Book - Level 4 by MIT SE-EDU.

== Summary of contributions

* *Major enhancement*: Added *the ability to add/remove appointments*
** What it does: Allows the user to add appointments to an existing patient or remove appointments from an existing patient.
** Justification: This feature improves the product significantly because the current edit command will overwrite the existing appointments whenever new appointments are added. The `addapt` and `remapt` commands allow user to add and
remove appointments from the existing list associated to a patient.
** Highlights: This enhancement extends the ability of the existing `add` and `edit` commands, which allows the user to create a patient with appointments.

* *Minor enhancement*:

* *Code contributed*: [https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#search=sickerin&sort=displayName&since=2019-02-10&until=2019-04-13&timeframe=day&reverse=false&repoSort=true[Project Code Dashboard]][https://github.com[Functional code addapt]]
[https://github.com[Functional code remapt]]
[https://github.com[Test code addapt]]
[https://github.com[Test code remapt]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.2` - `v1.4` (3 releases) on GitHub
** Enhancements to existing features:
*** _{to be added}_
** Documentation:
*** Added to and updated the User Guide
*** Added to and update the Developer Guide
*** Added to and updated the ContactUs.adoc
*** Added to and updated the AboutUs.adoc
** Community:
*** Reviewed and approved PRs of other team mates
** Tools:

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=aptremall]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

_{to be added}_
