= Ronald Santoso - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Giatros by CS2103 AY1819S2 W13-4

---

== Overview

Giatros is a desktop patient record application used to keep track of patient data in a hospital. Written in Java, the user interacts with it using a CLI, and it has a GUI created with JavaFX.
One of the main features of Giatros is its ability to track various allergies for each patient, something that medical professionals often overlook. This may lead to tragedy, such as death
due to drug allergy, as seen in this https://www.straitstimes.com/singapore/courts-crime/womans-death-from-drug-allergy-found-to-be-a-medical-misadventure[news article]. This software is built
upon an existing application: Address Book - Level 4 by MIT SE-EDU.

== Summary of contributions

* *Major enhancement*: Added *the ability to add/remove allergies*
** What it does: Allows the user to add allergies to an existing patient or remove allergies from an existing patient.
** Justification: This feature improves the product significantly because the current edit command will overwrite the existing allergies whenever new allergies are specified. The `addall` and `remall` commands allow user to add and
remove allergies from the existing list associated to a patient.
** Highlights: This enhancement extends the ability of the existing `add` and `edit` commands, which allows user to create a patient with allergies displayed as colourful tags.

* *Minor enhancement*:
** Added colours to the various allergies for easier identification.
** Changed the UI to show the search result of the first allergy when the patient is selected.

* *Code contributed*: [https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=githbub_wfxronald[Code contribution]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.0` - `v1.4` (5 releases) on GitHub
** Enhancements to existing features:
*** _{to be added}_
** Documentation:
*** _{to be added}_
** Community:
*** _{to be added}_
** Tools:
*** _{to be added}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=addremall]
include::../UserGuide.adoc[tag=authentication]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=addremall]
include::../DeveloperGuide.adoc[tag=usecase]
include::../DeveloperGuide.adoc[tag=manualtest1]
include::../DeveloperGuide.adoc[tag=manualtest2]
