=== Adding appointment to a patient

Prerequisites: List all patients using the `list` command. Multiple patients in the list. +

. Test case: `addapt`, `addapt 1` +
  Expected: An error will occur. Invalid command format.
. Test case: `addapt 1 apt/` +
  Expected: An error will occur. An error will occur. Appointment needs to follow the one of the valid formats: 'yyyy-MM-dd HH:mm:ss', 'yyyy-MM-dd HH:mm', 'yyyy-MM-dd HH' . An empty string is not a valid input.
. Test case: `addapt 1 apt/2019-04-01 14:30` +
  Expected: An error will occur. The appointment is already associated to the first patient.
. Test case: `addapt 1 apt/2019-02-29 14:30` +
  Expected: An error will occur. The 29th of Feb doesn't exist for 2019.
. Test case: `addapt 1 apt/2019-04-01 15:00` +
  Expected: Add appointment successful. The first patient is now associated with 2019-04-01 15:00 appointment.
. Test case: `addapt 1 apt/2019-04-01 14:30 apt/2019-04-01 18:00` +
  Expected: Add appointment successful. The first appointment is ignored, since it is already associated to the first patient. Aspirin appointment is added.

  See AppointmentTests.java for other examples for other valid/invalid appointments.

=== Removing appointment from a patient

Prerequisites: List all patients using the `list` command. Multiple patients in the list. +

. Test case: `remapt`, `remapt 1` +
  Expected: An error will occur. Invalid command format.
. Test case: `remapt 1 apt/` +
  Expected: An error will occur. Appointment needs to follow the one of the valid formats: 'yyyy-MM-dd HH:mm:ss', 'yyyy-MM-dd HH:mm', 'yyyy-MM-dd HH' . An empty string is not a valid input.
. Test case: `remapt 1 apt/2019-12-01 13:30` +
  Expected: An error will occur. Cannot find the appointment in the list of appointments for the first patient.
. Test case: `remapt 1 apt/2019-04-01 14:30` +
  Expected: Remove appointment successful. The first patient is now not associated with 2019-04-01 14:30 appointment anymore.
. Test case: `remapt 2 apt/2019-04-01 14:30 apt/2019-04-01 18:00` +
  Expected: Remove appointment successful. The second appointment is ignored, since it is not associated to the second patient. The first appointment is removed.

  See AppointmentTests.java for other examples for other invalid appointments.